name: Centralizer

on:
  push:
    paths:
      - '**/*'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Script
        run: |
          echo "Adding REST config to create Swagger"
